---
layout: default
title: "(Medium) Exceptional Server 👎"
parent: "Coding Test 💻"
grand_parent: "Etc 🛠"
nav_order: 2
---

## Table of contents
{: .no_toc .text-delta }

1. TOC
{:toc}

---

## 문제

```cpp
// 아래에 들어갈 exception을 정의하라

class Server {
private:
	static int load;
public:
	static int compute(long long A, long long B) {
		load += 1;
		if(A < 0) {
			throw std::invalid_argument("A is negative");
		}
		vector<int> v(A, 0);
		int real = -1, cmplx = sqrt(-1);
		if(B == 0) throw 0;
		real = (A/B)*real;
		int ans = v.at(B);
		return real + A - B*ans;
	}
	static int getLoad() {
		return load;
	}
};
int Server::load = 0;

int main() {
	int T; cin >> T;
	while(T--) {
		long long A, B;
		cin >> A >> B;

		/* Enter your code here. */

	}
	cout << Server::getLoad() << endl;
	return 0;
}
```

---

## 해답

```cpp
try {
    auto res = Server::compute(A, B);
    cout << res << endl;
} catch (const std::bad_alloc& e) {
    puts("Not enough memory");
} catch (const std::exception& e) {
    printf("Exception: %s\n", e.what());
} catch (...) {
    puts("Other Exception");
}
```